# for developing
version: '3'
services:
  mysql:
    #image: mysql:8.0.12
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: web_scraper
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
    #command: tail -f /dev/null
