apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-product-search-cronjob
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: gp2
  resources:
    requests:
      storage: 100Gi
