apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper-login-check-cronjob
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scraper-login-check-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
          - args:
            - bash
            - -c
            - cd /root/scraper/; java -jar web-scraper-server-*.jar --batch=login_check --spring.config.location=file:application.yaml >> /root/scraper/logs/login_check.log
            env:
            - name: SCRAPER_DB_PORT_3306_TCP_ADDR
              value: scraper-db
            image: tc3jp/scraper-app:dev1.0
            name: scraper-login-check-cronjob
            volumeMounts:
              - name: log
                mountPath: /root/scraper/logs
          volumes:
            - name: log
              persistentVolumeClaim:
                claimName: scraper-login-check-cronjob
