apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-purchase-history-cronjob
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
