apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper-product-search-cronjob
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scraper-product-search-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
          - args:
            - bash
            - -c
            - cd /root/scraper/;
              java -jar web-scraper-server-*.jar --batch=change_detection_check --target=product --spring.config.location=file:application.yaml &&
              java -jar web-scraper-server-*.jar --batch=product --spring.config.location=file:application.yaml &&
              java -jar web-scraper-server-*.jar --batch=group_products --spring.config.location=file:application.yaml
            env:
            - name: SCRAPER_DB_PORT_3306_TCP_ADDR
              value: scraper-db
            image: tc3jp/scraper-app:dev1.0
            name: scraper-product-search-cronjob
            imagePullPolicy: Always
            volumeMounts:
              - name: log
                mountPath: /root/scraper/logs
          volumes:
            - name: log
              persistentVolumeClaim:
                claimName: scraper-product-search-cronjob
