apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.local.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: scraper-app
  name: scraper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scraper-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.local.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: scraper-app
    spec:
      containers:
      - args:
        - bash
        - -c
        - sleep 10; cd /root/scraper/; java -jar web-scraper-server-*.jar --rest --spring.config.location=file:application.yaml
        env:
        - name: SCRAPER_DB_PORT_3306_TCP_ADDR
          value: scraper-db
        - name: SCRAPER_SOLR_PORT_9983_TCP_ADDR
          value: scraper-solr
        image: tc3jp/scraper-app:dev1.0
        name: scraper-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        resources: {}
        volumeMounts:
        - name: log
          mountPath: /root/scraper/logs
      restartPolicy: Always
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: scraper-app
