apiVersion: v1
kind: Service
metadata:
  name: scraper-solr-node-port
spec:
  type: NodePort
  selector:
    io.kompose.service: scraper-solr
  ports:
    - nodePort: 30023
      port: 8983
      protocol: TCP
      targetPort: 8983
