logging:
  level:
    root: INFO
    com.topcoder: DEBUG
    org.apache.http: OFF
    org.springframework.jdbc.core: DEBUG
    com.gargoylesoftware: OFF

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/web_scraper
    username: root
    password: mypassword

server:
  servlet-path: /api/v1
  port: 8085

solr:
  uri: http://localhost:9983/solr/ecsite_products
  load_batch_size: 100

scraper:
  matching:
    price_tolerance: 0.1
    mlt_score_threthold: 1.0


amazon:
  # amazon.com
  #  url: https://www.amazon.com/
  #  historyUrl: https://www.amazon.com/gp/your-account/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&orderFilter=
  #  productUrl: https://www.amazon.com/gp/product/
  # amazon.co.jp
  url: https://www.amazon.co.jp/
  historyUrl: https://www.amazon.co.jp/gp/your-account/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&orderFilter=
  productUrl: https://www.amazon.co.jp/gp/product/
  searchUrl:  https://www.amazon.co.jp/s?k=

  crawling:
    # Front page button
    loginButton: "#nav-link-accountList"

    # Login page
    loginPage:
      emailInput:    "input#ap_email"
      continueInput: "input#continue"
      passwordInput: "input#ap_password"
      submitButton:  "input#signInSubmit"

      captchaInput1st:  "input#captchacharacters"
      captchaImage1st:  "body > div > div.a-row.a-spacing-double-large > div.a-section > div > div > form > div.a-row.a-spacing-large > div > div > div.a-row.a-text-center > img"
      captchaSubmit1st: "body > div > div.a-row.a-spacing-double-large > div.a-section > div > div > form > div.a-section.a-spacing-extra-large > div > span > span > button"

      captchaInput2nd:  "input#auth-captcha-guess"
      captchaImage2nd:  "div#auth-captcha-image-container > img"

      mfaInput:       "input#auth-mfa-otpcode"
      mfaLoginButton: "input#auth-signin-button"

      verificationCodeSubmit: "span.cvf-widget-btn-verify > span > input"
      verificationCodeInput:  "input.cvf-widget-input-code"

      smsApproval: "#body > div > div > div.a-section.a-spacing-large > span.transaction-approval-word-break"

    homePage:
      ordersButton: "#nav-orders"
      # XPath Version
      #ordersButton: "//*[@id=\"nav-orders\"]"

    # Purchase history list page (Only this has xpath for experimental purpose.)
    purchaseHistoryListPage:
      orderDate:      "div.order-info > div > div > div > div:nth-of-type(1) > div > div:nth-of-type(1) > div:nth-of-type(2) > span"
      totalAmount:    "div.order-info > div > div > div > div:nth-of-type(1) > div > div:nth-of-type(2) > div:nth-of-type(2) > span"
      orderNumber:    "div.order-info > div > div > div > div:nth-of-type(2) > div:nth-of-type(1) > span:nth-of-type(2)"
      deliveryStatus: "div.shipment > div > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > span:nth-of-type(1)"
      # XPath Version
      #orderDate:      ".//div[contains(@class, \"order-info\")]/div/div/div/div[1]/div/div[1]/div[2]/span"
      #totalAmount:    ".//div[contains(@class, \"order-info\")]/div/div/div/div[1]/div/div[2]/div[2]/span"
      #orderNumber:    ".//div[contains(@class, \"order-info\")]/div/div/div/div[2]/div[1]/span[2]"
      #deliveryStatus: ".//div[contains(@class, \"shipment\")]/div/div[1]/div[1]/div[2]/span[1]"

      ordersBox:   "#ordersContainer > div.order"
      productsBox: "div.shipment > div > div > div > div:nth-of-type(1) > div > div.a-fixed-left-grid"
      # XPath Version
      #ordersBox:   "//*[@id=\"ordersContainer\"]/div[contains(@class, \"order\")]"
      #productsBox: ".//div[contains(@class, \"shipment\")]/div/div/div/div[1]/div/div[contains(@class, \"a-fixed-left-grid\")]"

      # the following css selectors are inside products_box
      productAnchor:      "div > div:nth-of-type(2) > div:nth-of-type(1) > a"
      productDistributor: "span.a-color-secondary"
      unitPrice:          "span.a-color-price"
      productQuantity:    "span.item-view-qty"
      # XPath Version
      #productAnchor:      ".//div/div[2]/div[1]/a"
      #productDistributor: ".//span[contains(@class, \"a-color-secondary\")]"
      #unitPrice:          ".//span[contains(@class, \"a-color-price\")]"
      #productQuantity:    ".//span[contains(@class, \"item-view-qty\")]"

      orderFilter: "#orderFilter"
      nextPage:    "#ordersContainer > div.a-row > div > ul > li.a-last > a"
      # XPath Version
      #orderFilter: "//*[@id=\"orderFilter\"]"
      #nextPage:    "//*[@id=\"ordersContainer\"]/div[@class=\"a-row\"]/div/ul/li[@class=\"a-last\"]/a"


    # Searh produ page
    SearchProductPage:
      productSelector:      "#search > div.sg-row > div.sg-col-20-of-24.sg-col-28-of-32.sg-col-16-of-20.sg-col.s-right-column.sg-col-32-of-36.sg-col-8-of-12.sg-col-12-of-16.sg-col-24-of-28 > div > span:nth-child(4) > div.s-result-list.sg-row > div:nth-child("
      adProductClass:       "AdHolder"
      productCodeAttribute: "data-asin"

    # Product detail page
    productDetailPage:
      prices:
        - "#priceblock_ourprice"
        - "#MediaMatrix > div > div > ul > li.selected > span > span.a-button-selected > span > a > span > span.a-color-price"
      name:             "#productTitle"
      salesRank:        "#SalesRank"
      productInfoTable: "#productDetails_detailBullets_sections1"
      modelNoLabels:
        - "div.wrapper.JPlocale > div.column.col1 > div > div.content.pdClearfix > div > div > table > tbody > tr:nth-child(8) > td.label"
        - "#prodDetails > div.wrapper.JPlocale > div.column.col1 > div > div.content.pdClearfix > div > div > table > tbody > tr:nth-child(2) > td.label"
        - "#detail_bullets_id > table > tbody > tr > td > div.content > ul > li:nth-child(3) > b"
        - "#detail_bullets_id > table > tbody > tr > td > div > ul > li:nth-child(2) > b"
        - "#detail_bullets_id > table > tbody > tr > td > div > ul > li:nth-child(3) > b"
        - "#prodDetails > div.wrapper.JPlocale > div.column.col1 > div > div.content.pdClearfix > div > div > table > tbody > tr:nth-child(2) > td.label"
        - "#detail_bullets_id > table > tbody > tr > td > div.content > ul > li:nth-child(2) > b"
      modelNoLabelValues:
        - "製品型番"
        - "製品型番"
        - "製品型番"
        - "メーカー型番"
        - "メーカー型番"
        - "モデル"
        - "製造元リファレンス"
      modelNoValues:
        - "div.wrapper.JPlocale > div.column.col1 > div > div.content.pdClearfix > div > div > table > tbody > tr:nth-child(8) > td.value"
        - "#prodDetails > div.wrapper.JPlocale > div.column.col1 > div > div.content.pdClearfix > div > div > table > tbody > tr:nth-child(2) > td.value"
        - "#detail_bullets_id > table > tbody > tr > td > div.content > ul > li:nth-child(3)"
        - "#detail_bullets_id > table > tbody > tr > td > div.content > ul > li:nth-child(2)"
        - "#detail_bullets_id > table > tbody > tr > td > div.content > ul > li:nth-child(3)"
        - "#prodDetails > div.wrapper.JPlocale > div.column.col1 > div > div.content.pdClearfix > div > div > table > tbody > tr:nth-child(2) > td.value"
        - "#detail_bullets_id > table > tbody > tr > td > div.content > ul > li:nth-child(2)"
