version: '3'
services:

  scraper-web-admin:
    image: scraper-web-admin:dev1.0
    build: ./nginx/admin
    container_name: "scraper-web-admin"
    ports:
      - 8080:80
    links:
      - scraper-app
    networks:
      scraper_net:
        ipv4_address: 10.1.0.5
    volumes:
      - ./nginx/admin/libs:/usr/share/nginx/html

  scraper-web-user:
    image: scraper-web-user:dev1.0
    build: ./nginx/user
    container_name: "scraper-web-user"
    ports:
      - 8081:80
    links:
      - scraper-app
    networks:
      scraper_net:
        ipv4_address: 10.1.0.6
    volumes:
      - ./nginx/user/libs:/usr/share/nginx/html

  scraper-app:
    image: scraper-app:dev1.0
    build: ./scraper
    container_name: "scraper-app"
    ports:
      - 8085:8085
    links:
      - scraper-db
      - scraper-solr
    depends_on:
      - scraper-db
    networks:
      scraper_net:
        ipv4_address: 10.1.0.7
    environment:
      SCRAPER_DB_PORT_3306_TCP_ADDR: 10.1.0.3
      SCRAPER_SOLR_PORT_9983_TCP_ADDR: 10.1.0.2
    volumes:
      - ./local-data/scraper/logs:/root/scraper/logs
    command: bash -c "sleep 10; cd /root/scraper/; java -jar web-scraper-server-*.jar --rest --spring.config.location=file:application.yaml"
    #tty: true

  scraper-db:
    build: ./mysql
    image: scraper-db:dev1.0
    container_name: "scraper-db"
    ports:
      - 3306:3306
    networks:
      scraper_net:
        ipv4_address: 10.1.0.3
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: web_scraper
#      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
    volumes:
#      - "./mysql/conf.d:/etc/mysql/conf.d"
#      - "./mysql/initdb.d:/root/mysql/initdb.d"
#      - "./mysql/jobs.d:/root/mysql/jobs.d"
      - "./local-data/mysql/data:/var/lib/mysql"
      - "./local-data/mysql/logs:/var/log/mysql"
      - "./local-data/mysql/backup:/root/mysql/backup"
  
  scraper-solr:
    image: scraper-solr:dev1.0
    container_name: "scraper-solr"
    build:
      context: ./solr/
    ports:
      - 9983:8983
    networks:
      scraper_net:
        ipv4_address: 10.1.0.2
    volumes:
      - search-store:/var/solr/data

networks:
  scraper_net:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16

volumes:
  search-store:
    driver: local
